<?php
/**
 * Sunday - Checkout Custom Field
 *
 * @category Sunday
 * @package  Sunday/CustomField
 * @author   Ali Us. <mealyus@gmail.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://github.com/mealyus/
 */
?>
<?php $order = $block->getOrder(); ?>
<?php if ($order): ?>
<section class="admin__page-section order-additional-information">
    <div class="admin__page-section-title">
        <strong class="title"><?= /* @escapeNotVerified */ __('Additional Information'); ?></strong>
    </div>
    <div id="<?= $block->getHtmlId() ?>"
         class="admin__page-section-content order-additional-information-container">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tr>
                        <th>Order Comments</th>
                        <td><?= $order->getDeliveryNote(); ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>